package sitegen

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// LoadTranslations 从 localesDir 加载指定语言的翻译文件。
// 文件名为 {lang}.yaml（如 zh-CN.yaml），内容为嵌套 YAML，
// 加载后扁平化为 "section.subsection.key" → "value" 的 map。
//
// 例 YAML:
//
//	nav:
//	  home: "首页"
//	  login: "登录"
//
// 扁平化后 → nav.home="首页", nav.login="登录"
func LoadTranslations(localesDir, lang string) (map[string]string, error) {
	yamlPath := filepath.Join(localesDir, lang+".yaml")
	data, err := os.ReadFile(yamlPath)
	if err != nil {
		return nil, fmt.Errorf("读取翻译文件 %s: %w", yamlPath, err)
	}

	// 先解析为通用 nested 结构（map[string]interface{}）
	var nested map[string]interface{}
	if err := yaml.Unmarshal(data, &nested); err != nil {
		return nil, fmt.Errorf("解析 YAML %s: %w", yamlPath, err)
	}

	// 扁平化
	flat := make(map[string]string)
	flatten("", nested, flat)

	return flat, nil
}

// flatten 递归把嵌套 map 扁平化为 dot-separated keys。
func flatten(prefix string, in map[string]interface{}, out map[string]string) {
	for k, v := range in {
		key := k
		if prefix != "" {
			key = prefix + "." + k
		}
		switch val := v.(type) {
		case map[string]interface{}:
			flatten(key, val, out)
		case map[interface{}]interface{}:
			// yaml.v3 对非顶层嵌套有时返回此类型，兼容处理
			converted := make(map[string]interface{})
			for mk, mv := range val {
				if sk, ok := mk.(string); ok {
					converted[sk] = mv
				}
			}
			flatten(key, converted, out)
		case string:
			out[key] = val
		case int:
			out[key] = fmt.Sprintf("%d", val)
		case bool:
			out[key] = fmt.Sprintf("%t", val)
		case nil:
			out[key] = ""
		default:
			out[key] = fmt.Sprintf("%v", val)
		}
	}
}

// GenerateI18nJS 把每语言翻译序列化为 {outDir}/i18n.{lang}.js。
// 格式：window.AnotifyI18n = {...};
// 供运行时 JS 文案用（partials.js / 各页 JS 通过 window.AnotifyI18n 查翻译）。
func (g *Generator) GenerateI18nJS(outDir string) error {
	for _, lang := range g.langs {
		vals, ok := g.translations[lang]
		if !ok {
			continue
		}

		// 排序 key 保证输出稳定（可复现构建）
		keys := make([]string, 0, len(vals))
		for k := range vals {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		// 构建 JSON 对象
		obj := make(map[string]string, len(vals))
		for _, k := range keys {
			obj[k] = vals[k]
		}

		jsonBytes, err := json.Marshal(obj)
		if err != nil {
			return fmt.Errorf("序列化 i18n JSON [%s]: %w", lang, err)
		}

		var sb strings.Builder
		sb.WriteString("/* Anotify i18n — auto-generated by sitegen. Do not edit. */\n")
		sb.WriteString("window.AnotifyI18n = ")
		sb.Write(jsonBytes)
		sb.WriteString(";\n")

		outPath := filepath.Join(outDir, "i18n."+lang+".js")
		if err := os.WriteFile(outPath, []byte(sb.String()), 0o644); err != nil {
			return fmt.Errorf("写入 %s: %w", outPath, err)
		}
	}
	return nil
}
