package sitegen

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// LoadTranslations loads the translation file for the given language from localesDir.
// The file is named {lang}.yaml (e.g. zh-CN.yaml) and contains nested YAML,
// which is flattened into a "section.subsection.key" → "value" map.
//
// Example YAML:
//
//	nav:
//	  home: "Home"
//	  login: "Sign in"
//
// Flattened → nav.home="Home", nav.login="Sign in"
func LoadTranslations(localesDir, lang string) (map[string]string, error) {
	yamlPath := filepath.Join(localesDir, lang+".yaml")
	data, err := os.ReadFile(yamlPath)
	if err != nil {
		return nil, fmt.Errorf("read translation file %s: %w", yamlPath, err)
	}

	// Parse into a generic nested structure (map[string]interface{}).
	var nested map[string]interface{}
	if err := yaml.Unmarshal(data, &nested); err != nil {
		return nil, fmt.Errorf("parse YAML %s: %w", yamlPath, err)
	}

	// Flatten.
	flat := make(map[string]string)
	flatten("", nested, flat)

	return flat, nil
}

// flatten recursively flattens a nested map into dot-separated keys.
func flatten(prefix string, in map[string]interface{}, out map[string]string) {
	for k, v := range in {
		key := k
		if prefix != "" {
			key = prefix + "." + k
		}
		switch val := v.(type) {
		case map[string]interface{}:
			flatten(key, val, out)
		case map[interface{}]interface{}:
			// yaml.v3 sometimes returns this type for non-top-level nests; handle it.
			converted := make(map[string]interface{})
			for mk, mv := range val {
				if sk, ok := mk.(string); ok {
					converted[sk] = mv
				}
			}
			flatten(key, converted, out)
		case string:
			out[key] = val
		case int:
			out[key] = fmt.Sprintf("%d", val)
		case bool:
			out[key] = fmt.Sprintf("%t", val)
		case nil:
			out[key] = ""
		default:
			out[key] = fmt.Sprintf("%v", val)
		}
	}
}

// GenerateI18nJS serializes each language's translations into {outDir}/i18n.{lang}.js.
// Format: window.AnotifyI18n = {...};
// Used by runtime JS strings (partials.js / per-page JS look up window.AnotifyI18n).
func (g *Generator) GenerateI18nJS(outDir string) error {
	for _, lang := range g.langs {
		vals, ok := g.translations[lang]
		if !ok {
			continue
		}

		// Sort keys for stable, reproducible output.
		keys := make([]string, 0, len(vals))
		for k := range vals {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		// Build the JSON object.
		obj := make(map[string]string, len(vals))
		for _, k := range keys {
			obj[k] = vals[k]
		}

		jsonBytes, err := json.Marshal(obj)
		if err != nil {
			return fmt.Errorf("serialize i18n JSON [%s]: %w", lang, err)
		}

		var sb strings.Builder
		sb.WriteString("/* Anotify i18n — auto-generated by sitegen. Do not edit. */\n")
		sb.WriteString("window.AnotifyI18n = ")
		sb.Write(jsonBytes)
		sb.WriteString(";\n")

		outPath := filepath.Join(outDir, "i18n."+lang+".js")
		if err := os.WriteFile(outPath, []byte(sb.String()), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", outPath, err)
		}
	}
	return nil
}
